services:
  webapp:
    image: alexgs99/node:2
    container_name: webapp
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - .:/simple-vtt
    working_dir: /simple-vtt/webapp
    networks:
      - app-network
#    environment:
#      - AUTH_CLIENT_ID
#      - AUTH_CLIENT_SECRET
#      - AUTH_DEFAULT_PASSWORD
#      - AUTH_ORIGIN_EXTERNAL
#      - AUTH_ORIGIN_INTERNAL
#      - AUTH_PATH_DISCOVERY
#      - COOKIE_ACCESS_TOKEN_TTL
#      - COOKIE_REFRESH_TOKEN_TTL
#      - COOKIE_VERIFY_TTL
#      - DATABASE_URL
#      - IRON_CURRENT_PWD
#      - IRON_PASSWORDS
#      - IRON_SEAL_TTL
#      - NEXT_PUBLIC_HASURA_SECRET
#      - WEBAPP_AUTH_API_KEY
#      - WEBAPP_BASE_URL
#      - WEBAPP_CDN_APP_ID
#      - WEBAPP_CORE_APP_ID
#      - WEBAPP_LOG_LEVEL
#      - WEBAPP_LOG_PATH
#      - WEBAPP_PORT
    command: /home/node/.volta/bin/npm run dev
#    depends_on:
#      - database
#    labels:
#      - "traefik.http.routers.webapp.rule=PathPrefix(`/`)"
#      - "traefik.http.routers.webapp.tls=true"
#      - "traefik.http.services.webapp.loadbalancer.server.port=${WEBAPP_PORT}"

networks:
  app-network:
    driver: bridge
    name: app-network
