# https://taskfile.dev

version: '3'

dotenv: ['.env']

vars:
  COMPOSE: docker compose
  NPM: npm

tasks:
  config:
    cmds:
      - "{{.COMPOSE}} config"
    desc: Print the compose file with variables expanded

  down:
    cmds:
      - "{{.COMPOSE}} down --remove-orphans"
    desc: Tear down the application

  up:
    cmds:
      - "{{.COMPOSE}} up -d"
    desc: Spin-up the application
