# https://taskfile.dev

version: '3'

includes:
  db: ./taskfiles/database.yml
  web: ./taskfiles/webapp.yml

dotenv: ['.env']

vars:
  COMPOSE: docker compose
  NPM: npm

tasks:
  config:
    cmds:
      - "{{.COMPOSE}} config"
    desc: Print the compose file with variables expanded

  down:
    cmds:
      - "{{.COMPOSE}} down --remove-orphans"
    desc: Tear down the application

  flyway:
    cmds:
      - "{{.COMPOSE}} run flyway"
    desc: Open an interactive shell for working with Flyway

  up:
    cmds:
      - "{{.COMPOSE}} up -d"
    desc: Spin-up the application
